import Header from "@/Components/Header/Header";
import "./globals.css";
import Aside from "@/Components/Aside/Aside";
import { Toaster } from "react-hot-toast";
import ContexValue from "@/ContextData/ContexValue";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <ContexValue>
          
     
        <Header />
   
     <div className="flex  items-start  ">
      <Aside/>
                <section className="w-full p-4     ">
                    {children}
                </section>
            </div>
            
      </ContexValue>
      <Toaster />
      </body>
    </html>
  );
}
